defaults:
  - _self_

model: ./model_conf/qwen_sigma
load_format: dummy

max_running_requests: 16384
chunked_prefill_size: 32000
max_prefill_tokens: 1048576

disable_custom_all_reduce: false
disable_radix_cache: true
disable_cuda_graph: false
disable_overlap_schedule: true
disable_chunked_prefix_cache: true
enable_torch_compile: false

mem_fraction_static: 0.5

trust_remote_code: true

log_level: debug

max_tokens_generated: 2

enable_benchmark: true
enforce_batching: true
profile_phase: null
