# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
model: ./model_conf/qwen_sigma
load_format: dummy
trust_remote_code: true

log_level: debug

disable_radix_cache: true
disable_overlap_schedule: true
disable_chunked_prefix_cache: true
enable_torch_compile: false
mem_fraction_static: 0.5

max_running_requests: 16384
max_prefill_tokens: 1048576
chunked_prefill_size: -1

max_tokens_generated: 2

enable_benchmark: true
enforce_batching: true 
profile_phase: null
