name: Unit Test

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*
  workflow_dispatch:

jobs:
  unit-test-correctness:
    runs-on: [self-hosted, linux/amd64]
    timeout-minutes: 120
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_CR_URI }}
          username: ${{ secrets.DOCKER_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      - name: Prepare Docker image
        run: |
          sudo docker pull ${{ secrets.AZURE_CR_URI }}/sglang/main:cuda
      - name: Test correctness
        env:
          TEST_OUTPUT_DIR: /mnt/output
          TEST_BATCH_SIZES: "16"
          TEST_SEQ_LENS: "4096"
          TEST_RANDOM_INPUT_COUNT: "1"
          TEST_REPEAT_COUNT: "1"
        run: |
          sudo docker run --privileged --net=host --gpus=all -v /mnt:/mnt --entrypoint /bin/bash \
            ${{ secrets.AZURE_CR_URI }}/sglang/main:cuda \
            /sgl-workspace/sglang/scripts/ltp_scripts/tests/test_correctness.sh
